---
- include: infrastructure.yml
- include: clan.yml
  when: clan

- name: Set up Artifactory
  hosts: artifactory
  become: True
  gather_facts: true

  roles:
    - teaming
    - nginx
    - postgresql
    - artifactory
