---
- import_playbook: common.yml

- name: Ensuring the configuration of the director host(s)
  hosts: director
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true

  roles:
    - director
...
