---
- import_playbook: base.yml

- hosts: infra
  become: True
  become_method: sudo
  gather_facts: False
  
  vars_files:
    - vault/certs/{{ realm }}.yml
  
  roles:
    - authentication
    - authorization
    - breakglass
