---
# The import_playbook is temporarily commented-out since it's not required for testing the osp-compute role
#- import_playbook: common.yml

- name: Ensuring configuration of OSP Compute host(s)
  hosts: osp-compute
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true

  roles:
    - osp-compute
...
